# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 640b738e0eb63f5e153a7f0963a53cde0179dd40a11a40075185f9c1e45d6362fc0a4b4a55684d7114b821314177371e1319daaf7e489cdb46691f269a3e80cf

test:
  secret_key_base: 5eed4f00f0c9514939df58d14ae09222a4054972cea61795a4b9de63c4c94d17a7cd88d20bd584cb0ff59af30243fa37f8db26ebb27a8517d7eafb1def374be2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
